apiVersion: v1
kind: Service
metadata:
  name: pyroscope
  namespace: observability
  labels: { app: pyroscope }
spec:
  selector: { app: pyroscope }
  ports:
    - { name: http, port: 4040, targetPort: 4040 }
